//POST https://salty-atoll-11726.herokuapp.com/api/persons
POST https://salty-atoll-11726.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "Mary Poppendieck",
    "number": "39-23-6423122"
}